from __future__ import annotations

from enum import Enum


class BotState(str, Enum):
    STARTING = "STARTING"
    SYNCING_MARKET = "SYNCING_MARKET"
    ANALYZING = "ANALYZING"
    WAITING_SIGNAL = "WAITING_SIGNAL"
    CONFIRMING_SIGNAL = "CONFIRMING_SIGNAL"
    CHECKING_RISK = "CHECKING_RISK"
    PLACING_ORDER = "PLACING_ORDER"
    ORDER_FILLED = "ORDER_FILLED"
    MONITORING_POSITION = "MONITORING_POSITION"
    TAKE_PROFIT_HIT = "TAKE_PROFIT_HIT"
    STOP_LOSS_HIT = "STOP_LOSS_HIT"
    CLOSING_POSITION = "CLOSING_POSITION"
    PAUSED = "PAUSED"
    ERROR = "ERROR"
