from __future__ import annotations

from enum import Enum


class BotState(str, Enum):
    INITIALIZING = "INITIALIZING"
    CONNECTING_EXCHANGE = "CONNECTING_EXCHANGE"
    SYNCING_SYMBOL = "SYNCING_SYMBOL"
    SYNCING_RULES = "SYNCING_RULES"
    WAITING_MARKET_DATA = "WAITING_MARKET_DATA"
    ANALYZING_MARKET = "ANALYZING_MARKET"
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    PLACING_ORDER = "PLACING_ORDER"
    POSITION_OPEN = "POSITION_OPEN"
    COOLDOWN = "COOLDOWN"
    PAUSED = "PAUSED"
    ERROR = "ERROR"
    STOPPED = "STOPPED"
